<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Native AOT にする -->
		<PublishAot>true</PublishAot>

		<!-- AOT 互換性を宣言：これにより IsTrimmable も true になり、トリミング警告が表示されるようになる -->
		<!-- 互換性を宣言せずに警告表示だけしたい場合は、代わりに EnableTrimAnalyzer を指定する -->
		<IsAotCompatible>true</IsAotCompatible>

		<!-- 分析の警告 -->
		<SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>

		<!-- 詳細な警告の表示 -->
		<TrimmerSingleWarn>false</TrimmerSingleWarn>

		<!-- AOT デプロイ最適化：デフォルトでは混合アプローチだが、Size / Speed を指定可能 -->
		<!--
		<OptimizationPreference>Speed</OptimizationPreference>
		-->

		<!-- トリミングの最小単位：デフォルトは full だが、partial にするとオプトインしたアセンブリのみをトリミングする -->
		<TrimMode>partial</TrimMode>
		<Platforms>x64</Platforms>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>

	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TestImplementComAotConsole.CsWin32\TestImplementComAotConsole.CsWin32.csproj" />
	</ItemGroup>

</Project>
